using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BulletController : AutoGeneratedMonoSingleton<BulletController>
{

    private BulletAI m_bulletPrefab;

    public void CreateBullet(Vector3 position, string origin, float hurt, float speed, Vector3 dir)
    {
        if (m_bulletPrefab == null) m_bulletPrefab = ResourcesManager.LoadEnemys<BulletAI>("Bullet");
        BulletAI bullet = Instantiate(m_bulletPrefab, transform);
        bullet.transform.position = position;        
        bullet.Init(origin, hurt, speed, dir);        
    }
}
