using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class App : AutoGeneratedMonoSingleton<App>
{
    private void Awake()
    {
        DontDestroyOnLoad(gameObject);
    }

    private bool m_pause = false;
    public bool Pause
    {
        get => m_pause;
        set
        {
            if (value != m_pause)
            {
                m_pause = value;
                Time.timeScale = m_pause ? 0.0f : 1.0f;
            }
        }
    }

    private bool m_isDeath = false;
    public bool IsDeath
    {
        get => m_isDeath;
        set
        {
            if (value != m_isDeath)
            {
                m_isDeath = value;
            }
        }
    }

}
