using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerData : AutoGeneratedSingleton<PlayerData>, IDisposable
{
    /// <summary>
    /// 0.0 ~ 1.0
    /// </summary>
    public float playerBlood { get; private set; }
    /// <summary>
    /// 0.0 ~ 1.0
    /// </summary>
    public float playerMagic { get; private set; }

    public PlayerData()
    {
        this.playerBlood = 1.0f;
        this.playerMagic = 1.0f;
    }


    public void SetPlayerData(ReplyType type, float value)
    {
        switch (type)
        {
            case ReplyType.Blood:
                float vBlood = playerBlood + value;
                playerBlood = vBlood > 1.0f ? 1.0f : vBlood < 0.0f ? 0.0f : vBlood;
                if (playerBlood <= 0)
                {
                    PlayerController.Instance.Death();
                }
                break;
            case ReplyType.Magic:
                float vMagic = playerMagic + value;
                playerMagic = vMagic > 1.0f ? 1.0f : vMagic < 0.0f ? 0.0f : vMagic;
                break;
        }
    }


    public void Dispose()
    {
        
    }
}
