using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SceneController : AutoGeneratedMonoSingleton<SceneController>
{
    private void Awake()
    {
        DontDestroyOnLoad(gameObject);
        m_sceneStack.Clear();
    }

    private Stack<SceneData> m_sceneStack = new Stack<SceneData>();

    public void SetNextScene(SceneData data)
    {
        m_sceneStack.Push(data);
    }

    public SceneData GetNextScene()
    {
        if (m_sceneStack.Count <= 0) return null;
        return m_sceneStack.Pop();
    }


}
