using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class VolumeSettingController : AutoGeneratedMonoSingleton<VolumeSettingController>
{

    public float VolumeBG { get; private set; }
    public float VolumeVideo { get; private set; }

    private void Awake()
    {
        DontDestroyOnLoad(gameObject);

        VolumeBG = PlayerPrefs.GetFloat("SliderVolumeBG", 1.0f);
        VolumeVideo = PlayerPrefs.GetFloat("SliderVolumeVideo", 1.0f);
    }

    public void SetVolumeBG(float value)
    {
        if (value != VolumeBG)
        {
            VolumeBG = value;
            EventManager<VolumeEvents>.Instance.TriggerEvent(VolumeEvents.VolumeBG, null);
            PlayerPrefs.SetFloat("SliderVolumeBG", VolumeBG);
        }
    }

    public void SetVolumeVideo(float value)
    {
        if (value != VolumeVideo)
        {
            VolumeVideo = value;
            EventManager<VolumeEvents>.Instance.TriggerEvent(VolumeEvents.VolumeVideo, null);
            PlayerPrefs.SetFloat("SliderVolumeVideo", VolumeVideo);
        }
    }
}
